apiVersion: apps/v1
kind: Deployment
metadata:
  name: recat-app-deployment
  labels:
    app: recat-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app-container
        image: pradeep82kumar/react-app:v1
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: NodePort
  selector:
    app: react-app
  ports:
  - protocol: TCP
    port: 8085
    targetPort: 8082
    nodePort: 30082  # NodePort value; it will expose the service on this port
